jobs:

  - name: job1
    description: Build Job 1
    repo_url: https://github.com/Anwesha-code/jenkins-job-template-engine.git
    branch: main
    build_command: echo Building Job 1

  - name: job2
    description: Build Job 2
    repo_url: https://github.com/Anwesha-code/jenkins-job-template-engine.git
    branch: main 
    build_command: echo Building Job 2